/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_wc_admin_note_actions` VALUES
(37,34,"connect","Connect","?page=wc-addons&section=helper","unactioned",0,"",NULL,NULL),
(38,35,"yes-please","Yes please!","https://woocommerce.us8.list-manage.com/subscribe/post?u=2c1434dc56f9506bf3c3ecd21&amp;id=13860df971&amp;SIGNUPPAGE=plugin","actioned",0,"",NULL,NULL),
(255,36,"learn-more","Learn more","https://docs.woocommerce.com/document/variable-product/?utm_source=inbox","actioned",0,"",NULL,NULL),
(1300,37,"learn-more","Learn more","https://docs.woocommerce.com/document/woocommerce-analytics/#variations-report","actioned",0,"",NULL,NULL),
(1301,38,"affirm-insight-first-product-and-payment","Yes","","actioned",0,"Thanks for your feedback",NULL,NULL),
(1302,38,"affirm-insight-first-product-and-payment","No","","actioned",0,"Thanks for your feedback",NULL,NULL),
(1843,39,"learn-more","Learn more","https://woocommerce.com/mobile/","actioned",0,"",NULL,NULL),
(1844,40,"online-clothing-store","Learn more","https://woocommerce.com/posts/starting-an-online-clothing-store/?utm_source=inbox","actioned",1,"",NULL,NULL),
(1845,41,"day-after-first-product","Learn more","https://docs.woocommerce.com/document/woocommerce-customizer/?utm_source=inbox","actioned",0,"",NULL,NULL),
(1846,42,"learn-more","Learn more","https://woocommerce.com/posts/how-to-make-your-online-store-stand-out/?utm_source=inbox","actioned",1,"",NULL,NULL),
(1847,43,"remove-legacy-coupon-menu","Remove legacy coupon menu","http://shop31.local/wp-admin/admin.php?page=wc-admin&action=remove-coupon-menu","actioned",1,"",NULL,NULL),
(1848,44,"need-some-inspiration","See success stories","https://woocommerce.com/success-stories/?utm_source=inbox","actioned",1,"",NULL,NULL),
(3289,45,"view-payment-gateways","Learn more","https://woocommerce.com/product-category/woocommerce-extensions/payment-gateways/","actioned",1,"",NULL,NULL),
(3290,46,"open-marketing-hub","Open marketing hub","http://shop31.local/wp-admin/admin.php?page=wc-admin&path=/marketing","actioned",0,"",NULL,NULL),
(3615,47,"tracking-opt-in","Activate usage tracking","","actioned",1,"",NULL,NULL),
(3616,48,"affirm-insight-first-sale","Yes","","actioned",0,"Thanks for your feedback",NULL,NULL),
(3617,48,"deny-insight-first-sale","No","","actioned",0,"Thanks for your feedback",NULL,NULL),
(6858,49,"customize-store-with-blocks","Learn more","https://woocommerce.com/posts/how-to-customize-your-online-store-with-woocommerce-blocks/?utm_source=inbox","actioned",1,"",NULL,NULL),
(7975,1,"wayflyer_q3_2021","Get funded","https://woocommerce.com/products/wayflyer/","actioned",1,"",NULL,NULL),
(7976,2,"eu_vat_changes_2021","Learn more about the EU tax regulations","https://woocommerce.com/posts/new-eu-vat-regulations","actioned",1,"",NULL,NULL),
(7977,3,"open_wc_paypal_payments_product_page","Learn more","https://woocommerce.com/products/woocommerce-paypal-payments/","actioned",1,"",NULL,NULL),
(7978,4,"upgrade_now_facebook_pixel_api","Upgrade now","plugin-install.php?tab=plugin-information&plugin=&section=changelog","actioned",1,"",NULL,NULL),
(7979,5,"learn_more_facebook_ec","Learn more","https://woocommerce.com/products/facebook/","unactioned",1,"",NULL,NULL),
(7980,6,"set-up-concierge","Schedule free session","https://wordpress.com/me/concierge","actioned",1,"",NULL,NULL),
(7981,7,"learn-more","Learn more","https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/?utm_source=inbox","unactioned",1,"",NULL,NULL),
(7982,8,"learn-more-ecomm-unique-shopping-experience","Learn more","https://docs.woocommerce.com/document/product-add-ons/?utm_source=inbox","actioned",1,"",NULL,NULL),
(7983,9,"watch-the-webinar","Watch the webinar","https://youtu.be/V_2XtCOyZ7o","actioned",1,"",NULL,NULL),
(7984,10,"learn-more","Learn more","https://woocommerce.com/posts/ecommerce-shipping-solutions-guide/?utm_source=inbox","actioned",1,"",NULL,NULL),
(7985,11,"boost-sales-marketing-guide","See marketing guide","https://developer.apple.com/apple-pay/marketing/?utm_source=inbox&utm_campaign=square-boost-sales","actioned",1,"",NULL,NULL),
(7986,12,"grow-your-business-marketing-guide","See marketing guide","https://developer.apple.com/apple-pay/marketing/?utm_source=inbox&utm_campaign=square-grow-your-business","actioned",1,"",NULL,NULL),
(7987,13,"add-apple-pay","Add Apple Pay","/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments","actioned",1,"",NULL,NULL),
(7988,13,"learn-more","Learn more","https://docs.woocommerce.com/document/payments/apple-pay/?utm_source=inbox&utm_medium=product&utm_campaign=wcpay_applepay","actioned",1,"",NULL,NULL),
(7989,14,"boost-sales-marketing-guide","See marketing guide","https://developer.apple.com/apple-pay/marketing/?utm_source=inbox&utm_campaign=wcpay-boost-sales","actioned",1,"",NULL,NULL),
(7990,15,"grow-your-business-marketing-guide","See marketing guide","https://developer.apple.com/apple-pay/marketing/?utm_source=inbox&utm_campaign=wcpay-grow-your-business","actioned",1,"",NULL,NULL),
(7991,16,"optimizing-the-checkout-flow","Learn more","https://woocommerce.com/posts/optimizing-woocommerce-checkout?utm_source=inbox","actioned",1,"",NULL,NULL),
(7992,17,"learn-more","Learn more","https://woocommerce.com/posts/first-things-customize-woocommerce/?utm_source=inbox","unactioned",1,"",NULL,NULL),
(7993,18,"qualitative-feedback-from-new-users","Share feedback","https://automattic.survey.fm/wc-pay-new","actioned",1,"",NULL,NULL),
(7994,19,"share-feedback","Share feedback","http://automattic.survey.fm/paypal-feedback","unactioned",1,"",NULL,NULL),
(7995,20,"learn-more","Learn about Instant Deposits eligibility","https://docs.woocommerce.com/document/payments/instant-deposits/?utm_source=inbox&utm_medium=product&utm_campaign=wcpay_instant_deposits","actioned",1,"",NULL,NULL),
(7996,21,"get-started","Get started","https://woocommerce.com/products/google-listings-and-ads","actioned",1,"",NULL,NULL),
(7997,22,"update-wc-subscriptions-3-0-15","View latest version","http://shop31.local/wp-admin/admin.php?page=wc-admin&page=wc-addons&section=helper","actioned",1,"",NULL,NULL),
(7998,23,"update-wc-core-5-4-0","How to update WooCommerce","https://docs.woocommerce.com/document/how-to-update-woocommerce/","actioned",1,"",NULL,NULL),
(7999,26,"get-woo-commerce-payments","Get WooCommerce Payments","admin.php?page=wc-admin&action=setup-woocommerce-payments","actioned",1,"",NULL,NULL),
(8000,27,"get-woocommerce-payments","Get WooCommerce Payments","admin.php?page=wc-admin&action=setup-woocommerce-payments","actioned",1,"",NULL,NULL),
(8001,28,"ppxo-pps-install-paypal-payments-1","View upgrade guide","https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/","actioned",1,"",NULL,NULL),
(8002,29,"ppxo-pps-install-paypal-payments-2","View upgrade guide","https://docs.woocommerce.com/document/woocommerce-paypal-payments/paypal-payments-upgrade-guide/","actioned",1,"",NULL,NULL),
(8003,30,"learn-more","Learn more","https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=vulnerability_comms","unactioned",1,"",NULL,NULL),
(8004,30,"dismiss","Dismiss","","actioned",0,"",NULL,NULL),
(8005,31,"learn-more","Learn more","https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=vulnerability_comms","unactioned",1,"",NULL,NULL),
(8006,31,"dismiss","Dismiss","","actioned",0,"",NULL,NULL),
(8007,32,"learn-more","Learn more","https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=vulnerability_comms","unactioned",1,"",NULL,NULL),
(8008,32,"dismiss","Dismiss","","actioned",0,"",NULL,NULL),
(8009,33,"learn-more","Learn more","https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/?utm_source=inbox_note&utm_medium=product&utm_campaign=vulnerability_comms","unactioned",1,"",NULL,NULL),
(8010,33,"dismiss","Dismiss","","actioned",0,"",NULL,NULL),
(8028,51,"notify-refund-returns-page","Edit page","http://shop31.local/wp-admin/post.php?post=1850&action=edit","actioned",0,"",NULL,NULL),
(8029,50,"update-db_done","Thanks!","http://shop31.local/wp-admin/admin.php?page=wc-status&tab=action-scheduler&s=woocommerce_run_update&status=pending&wc-hide-notice=update","actioned",1,"woocommerce_hide_notices_nonce","woocommerce_hide_notices_nonce","_wc_notice_nonce");
